SET BACKUPDRIVELETTER=Y
SET BACKUPSERVER=appledml.toronto.ca
SET BACKUPSHARE=migrate$
SET BACKUPROOT=data
SET BACKUPLOGS=logs
SET BACKUPSTATUS=logs
SET ALLSCRIPTSROOT=Scripts
SET SCRIPTROOT=Backup_UserProfiles
SET LOCALSCRIPTPATH=setup\usmt
SET LOCALSCRIPT=VHD_Capture.cmd

IF NOT EXIST %BACKUPDRIVELETTER%:\mig.data NET USE %BACKUPDRIVELETTER%: /DELETE
IF NOT EXIST %BACKUPDRIVELETTER%:\mig.data NET USE %BACKUPDRIVELETTER%: \\%BACKUPSERVER%\%BACKUPSHARE% /persistent:no
IF NOT EXIST %BACKUPDRIVELETTER%:\ GOTO :END

CD /D %BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\
powershell.exe -ExecutionPolicy Unrestricted %BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\%SCRIPTROOT%\EmptyTemp.ps1
IF EXIST "%BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture.log" DEL /q "%BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture.log"

systeminfo | find /i "system type" | find /i "X64"
IF %ERRORLEVEL% == 1 GOTO :X86
IF %ERRORLEVEL% == 0 GOTO :X64

:X64
IF NOT EXIST %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME% MKDIR %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%
CALL :CAPTUREDIAGNOSTICS
ECHO. >> %BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture_in_progress.log
ECHO ####### Started %DATE% - %TIME% ####### >>%BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture_start.log
IF EXIST "%BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\bin\disk2vhd.exe" "%BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\bin\disk2vhd.exe" * %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\%COMPUTERNAME%.vhd /accepteula
ECHO ####### Ended %DATE% - %TIME% ####### >>%BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture_end.log
IF ERRORLEVEL 0 DEL %BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture_in_progress.log
IF ERRORLEVEL 0 ECHO. >> %BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_done.log
GOTO :PROCEED

:X86
IF NOT EXIST %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME% MKDIR %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%
CALL :CAPTUREDIAGNOSTICS
ECHO. >> %BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture_in_progress.log
ECHO ####### Started %DATE% - %TIME% ####### >>%BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture_start.log
IF EXIST "%BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\bin\disk2vhd.exe" "%BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\bin\disk2vhd.exe" * %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\%COMPUTERNAME%.vhd /accepteula
ECHO ####### Ended %DATE% - %TIME% ####### >>%BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture_end.log
IF ERRORLEVEL 0 DEL %BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_capture_in_progress.log
IF ERRORLEVEL 0 ECHO. >> %BACKUPDRIVELETTER%:\%BACKUPLOGS%\%COMPUTERNAME%_done.log
GOTO :PROCEED

:PROCEED
:: SLEEP 60
 
IF NOT EXIST %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\USMT\File\C$\ GOTO END
PAUSE 300

:END
DEL C:\%LOCALSCRIPTPATH%\%LOCALSCRIPT%
EXIT

:CAPTUREDIAGNOSTICS
IF NOT EXIST %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics MKDIR %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics
for /F "usebackq tokens=1,2,3 delims=/" %%I IN (`echo %date%`) do set mydate=%%K_%%J_%%I
for /F "usebackq tokens=1,2,3 delims=:" %%I IN (`echo %time%`) do set mytime=%%I_%%J_%%K
IF NOT EXIST .\Captures MKDIR .\Captures
IF NOT EXIST %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics MKDIR %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics
:: Get Event logs
%BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\bin\psloglist -accepteula -s -f aew -x Application >> %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\EventLogs-Application.csv
%BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\bin\psloglist -accepteula -s -f aew -x System >> %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\EventLogs-Systems.csv
%BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\bin\psloglist -accepteula -s -f aew -x Security >> %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\EventLogs-Security.csv
%BACKUPDRIVELETTER%:\%ALLSCRIPTSROOT%\bin\psloglist -accepteula -s -x | find /i "KB" >> %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\EventLogs-KB.csv
echo sep=, > "%BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\_Processes.csv"
wmic process get /all /format:csv >> %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\_Processes.csv
echo sep=, > "%BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\_Services-security-info.csv"
wmic process get /all /format:csv >> %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\_Services-security-info.csv
echo sep=, > "%BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\_qfe.csv"
wmic qfe get description, FixComments, HotFixID, InstalledBy, InstalledOn, ServicePackInEffect, Caption /format:csv >> %BACKUPDRIVELETTER%:\%BACKUPROOT%\%COMPUTERNAME%\Diagnostics\_qfe.csv
EXIT /B